### ISSUE TITLE
Building / deploying status

### ISSUE THREAD

**Issue by lvandernoll** [therealsujitk/vercel-badge#7]
Thanks for the work! Is it possible to add a status for when the build is running, instead of only being able to display whether it has succeeded or failed?

**Comment by therealsujitk** [comment]
@lvandernoll, I've looked around and there are only two ways this could be possible, one is through the GitHub API, and the other is through the Vercel API.

- [The GitHub API](https://docs.github.com/en/rest/deployments/statuses) - The only problem with this is it would not work for people who want to use this badge in their private repositories. The way around this would be to let users pass a [GitHub API Token](https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api) as a parameter to this application.
- [The Vercel API](https://vercel.com/docs/rest-api/endpoints#get-a-deployment-by-id-or-url) - The only problem with this is that this would require users to pass their [Vercel API Access Token](https://vercel.com/guides/how-do-i-use-a-vercel-api-access-token) as a parameter to this application.

Obviously, both of these methods are **a severe security risk** since users (not just me, but anyone who looks at the URL parameter in the README) can gain complete access to your account using the API Key.

If you have an alternative solution I'd be glad to hear it, but as of now I can't find a feasible solution for all users (people with both public and private repositories) and hence I'll be closing this.
